#include "DeepForge/Import/Schema.h"

#include <algorithm>
#include <array>

namespace deepforge::import {
namespace {

using OT = OperationTag;

const std::array<OperationSchema, 39> kSchemas{{
    {OT::kAdaLayerNorm,
     "ADA_LAYER_NORM",
     {"compute_data_type", "forward_phase"},
     {},
     {"X", "SCALE", "BIAS", "EPSILON"},
     {"Y", "MEAN", "INV_VARIANCE"}},
    {OT::kAdaLayerNormBprop,
     "ADA_LAYER_NORM_BPROP",
     {"compute_data_type"},
     {},
     {"DY", "X", "SCALE", "MEAN", "INV_VARIANCE", "EPSILON"},
     {"DX", "DSCALE", "DBIAS"}},
    {OT::kBatchNorm,
     "BATCHNORM",
     {"compute_data_type", "peer_stats"},
     {},
     {"X", "SCALE", "BIAS", "EPSILON", "PREV_RUNNING_MEAN",
      "PREV_RUNNING_VAR", "MOMENTUM"},
     {"Y", "MEAN", "INV_VARIANCE", "NEXT_RUNNING_MEAN",
      "NEXT_RUNNING_VAR"}},
    {OT::kBatchNormInference,
     "BATCHNORM_INFERENCE",
     {"compute_data_type"},
     {},
     {"X", "SCALE", "BIAS", "MEAN", "INV_VARIANCE"},
     {"Y"}},
    {OT::kBlockScaleDequantize,
     "BLOCK_SCALE_DEQUANTIZE",
     {"compute_data_type", "block_size", "is_negative_scale"},
     {},
     {"X", "scale"},
     {"Y"}},
    {OT::kBlockScaleQuantize,
     "BLOCK_SCALE_QUANTIZE",
     {"compute_data_type", "block_size", "axis"},
     {},
     {"X"},
     {"Y", "scale"}},
    {OT::kBnFinalize,
     "BN_FINALIZE",
     {"compute_data_type"},
     {},
     {"SUM", "SQ_SUM", "SCALE", "BIAS", "EPSILON", "ACCUM_COUNT",
      "PREV_RUNNING_MEAN", "PREV_RUNNING_VAR", "MOMENTUM"},
     {"EQ_SCALE", "EQ_BIAS", "MEAN", "INV_VARIANCE",
      "NEXT_RUNNING_MEAN", "NEXT_RUNNING_VAR"}},
    {OT::kConcatenate,
     "CONCATENATE",
     {"axis", "in_place_index"},
     {},
     {},
     {"Y"},
     true},
    {OT::kConvDgrad,
     "CONV_DGRAD",
     {"compute_data_type", "pre_padding", "post_padding", "stride",
      "dilation", "math_mode"},
     {},
     {"W", "DY"},
     {"DX"}},
    {OT::kConvFprop,
     "CONV_FPROP",
     {"compute_data_type", "pre_padding", "post_padding", "stride",
      "dilation", "math_mode"},
     {},
     {"X", "W"},
     {"Y"}},
    {OT::kConvWgrad,
     "CONV_WGRAD",
     {"compute_data_type", "pre_padding", "post_padding", "stride",
      "dilation", "math_mode"},
     {},
     {"DY", "X"},
     {"DW"}},
    {OT::kDbn,
     "DBN",
     {"compute_data_type", "peer_stats"},
     {},
     {"DY", "X", "SCALE", "MEAN", "INV_VARIANCE"},
     {"DX", "DSCALE", "DBIAS"}},
    {OT::kDbnWeight,
     "DBN_WEIGHT",
     {"compute_data_type"},
     {},
     {"DY", "X", "SCALE", "MEAN", "INV_VARIANCE"},
     {"DSCALE", "DBIAS", "EQ_BIAS", "EQ_SCALE_DY", "EQ_SCALE_X"}},
    {OT::kGenStats,
     "GENSTATS",
     {"compute_data_type"},
     {},
     {"X"},
     {"SUM", "SQ_SUM"}},
    {OT::kInstanceNorm,
     "INSTANCE_NORM",
     {"compute_data_type", "forward_phase"},
     {},
     {"X", "SCALE", "BIAS", "EPSILON"},
     {"Y", "MEAN", "INV_VARIANCE"}},
    {OT::kInstanceNormBprop,
     "INSTANCE_NORM_BPROP",
     {"compute_data_type"},
     {},
     {"DY", "X", "SCALE", "MEAN", "INV_VARIANCE"},
     {"DX", "DSCALE", "DBIAS"}},
    {OT::kLayerNorm,
     "LAYER_NORM",
     {"compute_data_type", "forward_phase"},
     {},
     {"X", "SCALE", "BIAS", "EPSILON"},
     {"Y", "MEAN", "INV_VARIANCE"}},
    {OT::kLayerNormBprop,
     "LAYER_NORM_BPROP",
     {"compute_data_type"},
     {},
     {"DY", "X", "SCALE", "MEAN", "INV_VARIANCE", "EPSILON"},
     {"DX", "DSCALE", "DBIAS"}},
    {OT::kMatmul,
     "MATMUL",
     {"compute_data_type", "padding_value"},
     {},
     {"A", "B", "M_override", "N_override", "K_override"},
     {"C"}},
    {OT::kMatmulFp8,
     "MATMUL_FP8",
     {"compute_data_type"},
     {},
     {"A", "B", "Descale_A", "Descale_B", "M_override", "N_override",
      "K_override", "Scale_C"},
     {"C", "Amax_C"}},
    {OT::kMoeGroupedMatmul,
     "MOE_GROUPED_MATMUL",
     {"mode", "top_k"},
     {},
     {"Token", "Weight", "FirstTokenOffset", "TokenIndex", "TokenKs"},
     {"Output"}},
    {OT::kMoeGroupedMatmulBwd,
     "MOE_GROUPED_MATMUL_BWD",
     {},
     {},
     {"DOutput", "Token", "FirstTokenOffset"},
     {"DWeight"}},
    {OT::kPointwise,
     "POINTWISE",
     {"compute_data_type", "mode", "axis", "relu_lower_clip",
      "relu_upper_clip", "relu_lower_clip_slope", "swish_beta", "elu_alpha",
      "softplus_beta"},
     {},
     {"IN_0", "IN_1", "IN_2"},
     {"OUT_0"}},
    {OT::kReduction,
     "REDUCTION",
     {"compute_data_type", "mode", "is_deterministic"},
     {},
     {"X"},
     {"Y"}},
    {OT::kResample,
     "RESAMPLE",
     {"generate_index", "resample_mode", "padding_mode", "pre_padding",
      "post_padding", "stride", "window"},
     {},
     {"X"},
     {"Y", "Index"}},
    {OT::kReshape,
     "RESHAPE",
     {"compute_data_type", "dim", "stride", "reshape_mode"},
     {},
     {"X"},
     {"Y"}},
    {OT::kRmsNorm,
     "RMS_NORM",
     {"compute_data_type", "forward_phase"},
     {},
     {"X", "SCALE", "BIAS", "EPSILON"},
     {"Y", "INV_VARIANCE"}},
    {OT::kRmsNormBprop,
     "RMS_NORM_BPROP",
     {"compute_data_type"},
     {},
     {"DY", "X", "SCALE", "INV_VARIANCE"},
     {"DX", "DSCALE", "DBIAS"}},
    {OT::kRng,
     "RNG",
     {"distribution", "dim", "stride", "seed", "bernoulli_probability"},
     {},
     {"Seed", "Offset"},
     {"Y"}},
    {OT::kRope,
     "ROPE",
     {"compute_data_type", "output_scale", "rope_dim"},
     {},
     {"INPUT", "FREQS"},
     {"OUTPUT"}},
    {OT::kRopeBwd,
     "ROPE_BWD",
     {"compute_data_type", "output_scale", "rope_dim"},
     {},
     {"DY", "FREQS"},
     {"DX"}},
    {OT::kSdpa,
     "SDPA",
     {"generate_stats", "alibi_mask", "padding_mask", "dropout_probability",
      "attn_scale_value", "max_seq_len_kv", "mma_core_mode", "left_bound",
      "right_bound", "diagonal_alignment", "implementation", "is_mxfp8",
      "unfuse_fma"},
     {"rescale_threshold"},
     {"Q", "K", "V", "Attn_scale", "Bias", "SEQ_LEN_Q", "SEQ_LEN_KV",
      "Seed", "Offset", "Dropout_mask", "Dropout_scale", "Page_table_K",
      "Page_table_V", "Block_mask", "Descale_Q", "Descale_K", "Descale_V",
      "Descale_S", "Scale_S", "Scale_O", "SINK_TOKEN"},
     {"O", "Stats", "Max", "Sum_exp", "RNG_DUMP", "Amax_S", "Amax_O"}},
    {OT::kSdpaBwd,
     "SDPA_BWD",
     {"alibi_mask", "padding_mask", "dropout_probability",
      "attn_scale_value", "left_bound", "right_bound", "diagonal_alignment",
      "max_total_seq_len_q", "max_total_seq_len_kv",
      "is_deterministic_algorithm"},
     {},
     {"Q", "K", "V", "O", "dO", "Stats", "Attn_scale", "Bias",
      "SEQ_LEN_Q", "SEQ_LEN_KV", "Seed", "Offset", "Dropout_mask",
      "Dropout_scale", "Dropout_scale_inv", "SINK_TOKEN"},
     {"dQ", "dK", "dV", "dBias", "RNG_DUMP", "DSINK_TOKEN"}},
    {OT::kSdpaFp8Bwd,
     "SDPA_FP8_BWD",
     {"compute_data_type", "padding_mask", "dropout_probability",
      "left_bound", "right_bound", "diagonal_alignment", "attn_scale_value",
      "is_deterministic_algorithm", "is_mxfp8"},
     {"rescale_threshold"},
     {"Q", "Q_T", "K", "K_T", "V", "O", "dO", "dO_T", "dO_f16",
      "Stats", "Attn_scale", "Bias", "SEQ_LEN_Q", "SEQ_LEN_KV", "Seed",
      "Offset", "Dropout_mask", "Dropout_scale", "Dropout_scale_inv",
      "Descale_Q", "Descale_K", "Descale_V", "Descale_O", "Descale_dO",
      "Descale_dO_T", "Descale_K_T", "Descale_Q_T", "Descale_S",
      "Descale_dP", "Scale_dQ", "Scale_dK", "Scale_dV", "Scale_S",
      "Scale_dP", "SINK_TOKEN"},
     {"dQ", "dK", "dV", "Amax_dQ", "Amax_dK", "Amax_dV", "Amax_dP",
      "DSINK_TOKEN"}},
    {OT::kSdpaFp8Fwd,
     "SDPA_FP8_FWD",
     {"generate_stats", "alibi_mask", "padding_mask", "dropout_probability",
      "attn_scale_value", "max_seq_len_kv", "mma_core_mode", "left_bound",
      "right_bound", "diagonal_alignment", "implementation", "is_mxfp8",
      "unfuse_fma"},
     {"rescale_threshold"},
     {"Q", "K", "V", "Attn_scale", "Bias", "SEQ_LEN_Q", "SEQ_LEN_KV",
      "Seed", "Offset", "Dropout_mask", "Dropout_scale", "Page_table_K",
      "Page_table_V", "Block_mask", "Descale_Q", "Descale_K", "Descale_V",
      "Descale_S", "Scale_S", "Scale_O", "SINK_TOKEN"},
     {"O", "Stats", "Max", "Sum_exp", "RNG_DUMP", "Amax_S", "Amax_O"}},
    {OT::kSdpaMxfp8Bwd,
     "SDPA_MXFP8_BWD",
     {"compute_data_type", "padding_mask", "dropout_probability",
      "left_bound", "right_bound", "diagonal_alignment", "attn_scale_value",
      "is_deterministic_algorithm", "is_mxfp8"},
     {"rescale_threshold"},
     {"Q", "Q_T", "K", "K_T", "V", "O", "dO", "dO_T", "dO_f16",
      "Stats", "Attn_scale", "Bias", "SEQ_LEN_Q", "SEQ_LEN_KV", "Seed",
      "Offset", "Dropout_mask", "Dropout_scale", "Dropout_scale_inv",
      "Descale_Q", "Descale_K", "Descale_V", "Descale_O", "Descale_dO",
      "Descale_dO_T", "Descale_K_T", "Descale_Q_T", "Descale_S",
      "Descale_dP", "Scale_dQ", "Scale_dK", "Scale_dV", "Scale_S",
      "Scale_dP", "SINK_TOKEN"},
     {"dQ", "dK", "dV", "Amax_dQ", "Amax_dK", "Amax_dV", "Amax_dP",
      "DSINK_TOKEN"}},
    {OT::kSdpaMxfp8Fwd,
     "SDPA_MXFP8_FWD",
     {"generate_stats", "alibi_mask", "padding_mask", "dropout_probability",
      "attn_scale_value", "max_seq_len_kv", "mma_core_mode", "left_bound",
      "right_bound", "diagonal_alignment", "implementation", "is_mxfp8",
      "unfuse_fma"},
     {"rescale_threshold"},
     {"Q", "K", "V", "Attn_scale", "Bias", "SEQ_LEN_Q", "SEQ_LEN_KV",
      "Seed", "Offset", "Dropout_mask", "Dropout_scale", "Page_table_K",
      "Page_table_V", "Block_mask", "Descale_Q", "Descale_K", "Descale_V",
      "Descale_S", "Scale_S", "Scale_O", "SINK_TOKEN"},
     {"O", "Stats", "Max", "Sum_exp", "RNG_DUMP", "Amax_S", "Amax_O"}},
    {OT::kSlice,
     "SLICE",
     {"compute_data_type", "slices", "slice_strides"},
     {},
     {"X"},
     {"Y"}},
    {OT::kTranspose,
     "TRANSPOSE",
     {"compute_data_type", "permutation"},
     {},
     {"X"},
     {"Y"}},
}};

constexpr std::array<std::string_view, 50> kPointwiseModes{{
    "ADD",          "MUL",        "SQRT",       "MAX",
    "MIN",          "RELU_FWD",   "TANH_FWD",   "SIGMOID_FWD",
    "ELU_FWD",      "GELU_FWD",   "SOFTPLUS_FWD", "SWISH_FWD",
    "RELU_BWD",     "TANH_BWD",   "SIGMOID_BWD", "ELU_BWD",
    "GELU_BWD",     "SOFTPLUS_BWD", "SWISH_BWD", "ERF",
    "IDENTITY",     "GELU_APPROX_TANH_BWD", "GELU_APPROX_TANH_FWD",
    "GEN_INDEX",    "BINARY_SELECT", "EXP",       "LOG",
    "NEG",          "MOD",        "POW",        "ABS",
    "CEIL",         "COS",        "FLOOR",      "RSQRT",
    "SIN",          "LOGICAL_NOT", "TAN",        "SUB",
    "ADD_SQUARE",   "DIV",        "CMP_EQ",     "CMP_NEQ",
    "CMP_GT",       "CMP_GE",     "CMP_LT",     "CMP_LE",
    "LOGICAL_AND",  "LOGICAL_OR", "RECIPROCAL",
}};

constexpr std::array<std::string_view, 9> kReductionModes{{
    "ADD", "MUL", "MIN", "MAX", "AMAX", "AVG", "NORM1", "NORM2",
    "MUL_NO_ZEROS",
}};

}  // namespace

std::span<OperationSchema const> operation_schemas() noexcept {
    return kSchemas;
}

OperationSchema const* find_operation_schema(OperationTag tag) noexcept {
    auto const it = std::find_if(
        kSchemas.begin(), kSchemas.end(),
        [tag](OperationSchema const& schema) { return schema.tag == tag; });
    return it == kSchemas.end() ? nullptr : &*it;
}

std::span<std::string_view const> pointwise_modes() noexcept {
    return kPointwiseModes;
}

std::span<std::string_view const> reduction_modes() noexcept {
    return kReductionModes;
}

bool is_pointwise_mode(std::string_view mode) noexcept {
    return std::find(kPointwiseModes.begin(), kPointwiseModes.end(), mode) !=
           kPointwiseModes.end();
}

bool is_reduction_mode(std::string_view mode) noexcept {
    return std::find(kReductionModes.begin(), kReductionModes.end(), mode) !=
           kReductionModes.end();
}

std::optional<std::size_t>
pointwise_input_count(std::string_view mode) noexcept {
    if (!is_pointwise_mode(mode)) {
        return std::nullopt;
    }
    if (mode == "BINARY_SELECT") {
        return 3;
    }
    constexpr std::array<std::string_view, 25> kBinaryModes{{
        "ADD",          "MUL",       "DIV",      "ADD_SQUARE",
        "SUB",          "CMP_EQ",    "CMP_NEQ",  "CMP_GT",
        "CMP_GE",       "CMP_LT",    "CMP_LE",   "LOGICAL_AND",
        "LOGICAL_OR",   "MIN",       "MAX",      "MOD",
        "RELU_BWD",     "TANH_BWD",  "SIGMOID_BWD",
        "ELU_BWD",      "GELU_BWD",  "SOFTPLUS_BWD",
        "SWISH_BWD",    "GELU_APPROX_TANH_BWD", "POW",
    }};
    return std::find(kBinaryModes.begin(), kBinaryModes.end(), mode) !=
                   kBinaryModes.end()
               ? 2
               : 1;
}

}  // namespace deepforge::import
